
import { FaRegStar } from "react-icons/fa";
import { PiCoatHangerThin } from "react-icons/pi";
import { BsJournalAlbum } from "react-icons/bs";
import { CiForkAndKnife } from "react-icons/ci";
import { IoBedOutline } from "react-icons/io5";
import { BiMoviePlay } from "react-icons/bi";
import { CiLock } from "react-icons/ci";
import { MdOutlineFireplace } from "react-icons/md";
import { IoBookOutline } from "react-icons/io5";
import { GiFullMotorcycleHelmet } from "react-icons/gi";
import { PiMountains } from "react-icons/pi";
import { TbBeach } from "react-icons/tb";
import { CiHeart } from "react-icons/ci";
import { BsStars } from "react-icons/bs";
import { CiCalendarDate } from "react-icons/ci";
import { CiDesktop } from "react-icons/ci";
import { CiTrophy } from "react-icons/ci";
import { MdOutlineBathtub } from "react-icons/md";
import { FaShower } from "react-icons/fa";
import { IoHomeOutline } from "react-icons/io5";


const iconMap = {
    FaRegStar,
    PiCoatHangerThin,
    BsJournalAlbum,
    CiForkAndKnife,
    IoBedOutline,
    BiMoviePlay,
    CiLock,
    MdOutlineFireplace,
    IoBookOutline,
    GiFullMotorcycleHelmet,
    PiMountains,
    TbBeach,
    CiHeart,
    BsStars,
    CiCalendarDate,
    CiDesktop,
    CiTrophy,
    MdOutlineBathtub,
    FaShower,
    IoHomeOutline

};

const Hosts = [
    {
        id: 1,
        image: "https://www.w3schools.com/w3images/nature.jpg",
        name: "Polly",
        keyword: "adventurous",
        city: "San Francisco",
        country: "USA",
        totalYears: 10,
        identity: 112223344,
        number: 1112222,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [1, 2, 3],
        locations: [
            {
                id: 1,
                image: "https://www.w3schools.com/w3images/nature.jpg",
                live: true,
                title: "Sleepover at Polly Pocket’s Compact",
                host: {
                    id: 1,
                    image: "https://www.w3schools.com/w3images/nature.jpg",
                    name: "Polly",
                    keyword: "adventurous",
                    city: "San Francisco",
                    country: "USA",
                    totalYears: 10,
                    identity: 112223344,
                    number: 1112222,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [1, 2, 3]
                },
                hostId: 1,
                city: "San Francisco",
                country: "USA",

                price: "89",
                guestrooms: 1,
                beds: 2,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-09-30",
                activities: [
                    { icon: iconMap.FaRegStar, name: "Picnic in the Garden", description: "Enjoy a relaxing picnic in the beautifully manicured garden." },
                    { icon: iconMap.PiCoatHangerThin, name: "Movie Night", description: "Watch your favorite movies in a cozy setting." },
                    { icon: iconMap.BsJournalAlbum, name: "DIY Crafts", description: "Get creative with various craft projects." },
                    { icon: iconMap.CiForkAndKnife, name: "Board Games", description: "Play a selection of board games with your friends." },

                ],
                shortDescription: "Experience a fun-filled sleepover at a charming compact, perfect for a cozy getaway.",
                whatYoullDo: "90s kids rule at sleepovers. But you already knew that. So I wanted this sleepover to feel like you're still actually in the '90s! Just picture it-crafting, throwback snacks, Polaroid cameras... it's going to be AMAZING. Basically, I turned my Slumber Party Fun compact into a time machine where your imagination can run wild. Because there's no greater adventure than the one you create for yourself",
                location: { latitude: 37.7749, longitude: -122.4194 }
            },
            {
                id: 2,
                image: "https://www.w3schools.com/w3images/lights.jpg",
                live: true,
                title: "Playdate at Polly Pocket’s Compact",
                host: {
                    id: 1,
                    image: "https://www.w3schools.com/w3images/nature.jpg",
                    name: "Polly",
                    keyword: "adventurous",
                    city: "San Francisco",
                    country: "USA",
                    totalYears: 10,
                    identity: 112223344,
                    number: 1112222,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [1, 2, 3]
                },
                hostId: 1,
                price: 35,
                city: "Los Angeles",
                country: "USA",
                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-10-15",
                activities: [
                    { icon: iconMap.IoBedOutline, name: "City Tour", description: "Explore the vibrant city of Los Angeles with a guided tour." },
                    { icon: iconMap.BsJournalAlbum, name: "Food Truck Festival", description: "Taste a variety of dishes from local food trucks." },
                    { icon: iconMap.CiHeart, name: "Art Gallery Visit", description: "Visit local art galleries and appreciate contemporary art." },
                    { icon: iconMap.CiLock, name: "Live Music", description: "Experience live music performances at a nearby venue." },
                ],
                shortDescription: "Join Polly Pocket for a fun playdate in the heart of Los Angeles.",
                whatYoullDo: "90s kids rule at sleepovers. But you already knew that. So I wanted this sleepover to feel like you're still actually in the '90s! Just picture it-crafting, throwback snacks, Polaroid cameras... it's going to be AMAZING. Basically, I turned my Slumber Party Fun compact into a time machine where your imagination can run wild. Because there's no greater adventure than the one you create for yourself",
                location: { latitude: 34.0522, longitude: -118.2437 }
            },
            {
                id: 3,
                image: "https://www.w3schools.com/w3images/falls2.jpg",
                live: true,
                title: "Go VIP with Kevin Hart",
                host: {
                    id: 1,
                    image: "https://www.w3schools.com/w3images/nature.jpg",
                    name: "Polly",
                    keyword: "adventurous",
                    city: "San Francisco",
                    country: "USA",
                    totalYears: 10,
                    identity: 112223344,
                    number: 1112222,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [1, 2, 3]
                },
                hostId: 1,
                price: 76,
                city: "New York",
                country: "USA",
                guestrooms: 2,
                beds: 3,
                bedrooms: 2,
                baths: 2,
                closingDate: "2024-08-30",
                activities: [
                    { icon: iconMap.FaRegStar, name: "Comedy Show", description: "Enjoy a live comedy performance by Kevin Hart." },
                    { icon: iconMap.FaShower, name: "Q&A Session", description: "Participate in a Q&A session with the comedian." },
                    { icon: iconMap.MdOutlineBathtub, name: "Backstage Tour", description: "Get an exclusive backstage tour of the event venue." },
                    { icon: iconMap.BsStars, name: "Meet & Greet", description: "Meet Kevin Hart and get an autograph." },
                    { icon: iconMap.TbBeach, name: "Dinner with Kevin", description: "Have dinner with Kevin Hart and other VIP guests." },
                ],
                shortDescription: "Experience a VIP event with Kevin Hart, including comedy shows and exclusive access.",
                whatYoullDo: "Attend a comedy show, enjoy backstage access, and meet Kevin Hart in person.",
                location: { latitude: 40.7128, longitude: -74.0060 }
            },
        ]
    },
    {
        id: 2,
        image: "https://www.w3schools.com/w3images/fjords.jpg",
        name: "John",
        keyword: "relaxing",
        city: "Reykjavik",
        country: "Iceland",
        totalYears: 5,
        identity: 223344556,
        number: 2223333,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [4, 5],
        locations: [
            {
                id: 4,
                image: "https://www.w3schools.com/w3images/forest.jpg",
                live: false,
                title: "Join a living room session with Doja",
                host: {
                    id: 2,
                    image: "https://www.w3schools.com/w3images/fjords.jpg",
                    name: "John",
                    keyword: "relaxing",
                    city: "Reykjavik",
                    country: "Iceland",
                    totalYears: 5,
                    identity: 223344556,
                    number: 2223333,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [4, 5]
                },
                hostId: 2,
                city: "Austin",
                country: "USA",
                isComingSoon: true,
                coming: "October",
                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-12-01",
                activities: [
                    { icon: iconMap.PiCoatHangerThin, name: "Live Music Session", description: "Join Doja Cat for an exclusive live music session." },
                    { icon: iconMap.BsJournalAlbum, name: "Interactive Q&A", description: "Engage in an interactive Q&A with the artist." },
                    { icon: iconMap.CiForkAndKnife, name: "Behind-the-Scenes", description: "Get a behind-the-scenes look at Doja's creative process." },
                    { icon: iconMap.IoHomeOutline, name: "Exclusive Merch", description: "Access exclusive merchandise only available to attendees." },
                    { icon: iconMap.FaShower, name: "Virtual Meet & Greet", description: "Participate in a virtual meet & greet with Doja Cat." },
                ],
                shortDescription: "Be part of an exclusive living room session with Doja Cat, featuring live music and more.",
                whatYoullDo: "Experience a live session, Q&A, and exclusive content with Doja Cat.",
                location: { latitude: 30.2672, longitude: -97.7431 }
            },
            {
                id: 5,
                image: "https://www.w3schools.com/w3images/mountains.jpg",
                live: false,
                title: "Discover the Secrets of the Mountains",
                host: {
                    id: 2,
                    image: "https://www.w3schools.com/w3images/fjords.jpg",
                    name: "John",
                    keyword: "relaxing",
                    city: "Reykjavik",
                    country: "Iceland",
                    totalYears: 5,
                    identity: 223344556,
                    number: 2223333,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [4, 5]
                },
                hostId: 2,
                isComingSoon: true,
                coming: "November",
                city: "Denver",
                country: "USA",
                guestrooms: 2,
                beds: 4,
                bedrooms: 2,
                baths: 2,
                closingDate: "2024-11-15",
                activities: [
                    { icon: iconMap.MdOutlineBathtub, name: "Mountain Hiking", description: "Explore beautiful mountain trails with an experienced guide." },
                    { icon: iconMap.CiTrophy, name: "Wildlife Viewing", description: "Spot local wildlife and learn about their habitats." },
                    { icon: iconMap.CiDesktop, name: "Rock Climbing", description: "Try rock climbing with all the necessary equipment provided." },

                ],
                shortDescription: "Join us for a mountain adventure, exploring trails and enjoying nature's beauty.",
                whatYoullDo: "Hike, climb, and experience the natural wonders of the mountains with guided activities.",
                location: { latitude: 39.7392, longitude: -104.9903 }
            },
        ]

    },
    {
        id: 3,
        image: "https://www.w3schools.com/w3images/lights.jpg",
        name: "Maria",
        keyword: "cultural",
        city: "Rome",
        country: "Italy",
        totalYears: 8,
        identity: 334455667,
        number: 3334444,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [6, 7, 8],
        locations: [
            {
                id: 6,
                image: "https://www.w3schools.com/w3images/bridge.jpg",
                live: false,
                title: "Virtual Tour of Iconic Bridges",
                host: {
                    id: 3,
                    image: "https://www.w3schools.com/w3images/lights.jpg",
                    name: "Maria",
                    keyword: "cultural",
                    city: "Rome",
                    country: "Italy",
                    totalYears: 8,
                    identity: 334455667,
                    number: 3334444,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [6, 7, 8]
                },
                hostId: 3,
                isComingSoon: true,
                coming: "March",
                city: "San Francisco",
                country: "USA",
                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-10-10",
                activities: [
                    { icon: iconMap.FaRegStar, name: "Virtual Bridge Walk", description: "Experience iconic bridges through a virtual tour." },
                    { icon: iconMap.CiCalendarDate, name: "Interactive Q&A", description: "Engage with experts about bridge engineering." },
                    { icon: iconMap.BsStars, name: "Historical Insights", description: "Learn about the history and significance of famous bridges." },

                ],
                shortDescription: "Join a virtual tour exploring the world’s most iconic bridges from the comfort of your home.",
                whatYoullDo: "Experience a guided virtual tour, engage in interactive sessions, and learn about bridge design.",
                location: { latitude: 37.7749, longitude: -122.4194 }
            },
            {
                id: 7,
                image: "https://www.w3schools.com/w3images/forest.jpg",
                live: true,
                title: "Stay in a Cozy Cabin",
                host: {
                    id: 3,
                    image: "https://www.w3schools.com/w3images/lights.jpg",
                    name: "Maria",
                    keyword: "cultural",
                    city: "Rome",
                    country: "Italy",
                    totalYears: 8,
                    identity: 334455667,
                    number: 3334444,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [6, 7, 8]
                },
                hostId: 3,
                price: 120,
                city: "Aspen",
                country: "USA",
                guestrooms: 2,
                beds: 3,
                bedrooms: 2,
                baths: 2,
                closingDate: "2024-12-01",
                activities: [
                    { icon: iconMap.TbBeach, name: "Mountain Hiking", description: "Explore nearby hiking trails and enjoy the natural beauty." },
                    { icon: iconMap.CiHeart, name: "Campfire Evenings", description: "Gather around a campfire for storytelling and roasting marshmallows." },

                ],
                shortDescription: "Escape to a cozy cabin in the mountains, perfect for a relaxing retreat with various outdoor activities.",
                whatYoullDo: "Stay in a comfortable cabin, enjoy outdoor activities, and relax in a serene mountain setting.",
                location: { latitude: 39.1910, longitude: -106.8175 }
            },
            {
                id: 8,
                image: "https://www.w3schools.com/w3images/mountains.jpg",
                live: false,
                title: "Relax by the Lake",
                host: {
                    id: 3,
                    image: "https://www.w3schools.com/w3images/lights.jpg",
                    name: "Maria",
                    keyword: "cultural",
                    city: "Rome",
                    country: "Italy",
                    totalYears: 8,
                    identity: 334455667,
                    number: 3334444,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [6, 7, 8]
                },
                hostId: 3,
                isComingSoon: true,
                coming: "October",
                city: "Lake Tahoe",
                country: "USA",
                guestrooms: 2,
                beds: 2,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-11-20",
                activities: [
                    { icon: iconMap.PiMountains, name: "Lake Kayaking", description: "Enjoy a peaceful kayak ride on the lake." },
                    { icon: iconMap.GiFullMotorcycleHelmet, name: "Nature Walk", description: "Take a scenic walk around the lake and surrounding forest." },
                    { icon: iconMap.IoBookOutline, name: "Fishing", description: "Relax by the lake and try fishing for local species." },
                    { icon: iconMap.MdOutlineFireplace, name: "Picnic", description: "Have a delightful picnic by the lakeside." },
                    { icon: iconMap.FaRegStar, name: "Wildlife Watching", description: "Observe wildlife in their natural environment." },
                ],
                shortDescription: "Relax and unwind by the beautiful lake with activities such as kayaking, fishing, and nature walks.",
                whatYoullDo: "Enjoy serene lake activities, explore nature, and relax in a tranquil environment.",
                location: { latitude: 38.9396, longitude: -120.0554 }
            },
        ]
    },
    {
        id: 4,
        image: "https://www.w3schools.com/w3images/mountains.jpg",
        name: "Akira",
        keyword: "adventurous",
        city: "Kyoto",
        country: "Japan",
        totalYears: 6,
        identity: 445566778,
        number: 4445555,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [9, 10],
        locations: [
            {
                id: 9,
                image: "https://www.w3schools.com/w3images/forest.jpg",
                live: true,
                title: "Forest Adventure",
                host: {
                    id: 4,
                    image: "https://www.w3schools.com/w3images/mountains.jpg",
                    name: "Akira",
                    keyword: "adventurous",
                    city: "Kyoto",
                    country: "Japan",
                    totalYears: 6,
                    identity: 445566778,
                    number: 4445555,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [9, 10]
                },
                hostId: 4,
                soldOut: true,
                city: "Seattle",
                country: "USA",
                guestrooms: 3,
                beds: 6,
                bedrooms: 3,
                baths: 2,
                closingDate: "2024-09-15",
                activities: [
                    { icon: iconMap.CiLock, name: "Forest Hike", description: "Embark on a guided hike through lush forest trails." },
                    { icon: iconMap.BiMoviePlay, name: "Bird Watching", description: "Spot various bird species and learn about their habitats." },
                    { icon: iconMap.IoBedOutline, name: "Campfire Stories", description: "Gather around a campfire for storytelling and s'mores." },
                    { icon: iconMap.BsJournalAlbum, name: "Photography Walk", description: "Capture the beauty of the forest with expert photography tips." },
                    { icon: iconMap.FaRegStar, name: "Wildlife Tracking", description: "Learn about local wildlife and their tracks during a guided walk." },
                ],
                shortDescription: "Immerse yourself in a forest adventure with guided hikes, wildlife tracking, and more.",
                whatYoullDo: "Experience the forest through various activities including hiking, bird watching, and photography.",
                location: { latitude: 47.6062, longitude: -122.3321 }
            },
            {
                id: 10,
                image: "https://www.w3schools.com/w3images/bridge.jpg",
                live: true,
                title: "Iconic Bridge Tour",
                host: {
                    id: 4,
                    image: "https://www.w3schools.com/w3images/mountains.jpg",
                    name: "Akira",
                    keyword: "adventurous",
                    city: "Kyoto",
                    country: "Japan",
                    totalYears: 6,
                    identity: 445566778,
                    number: 4445555,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [9, 10]
                },
                hostId: 4,
                price: 65,
                city: "New York",
                country: "USA",
                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-10-05",
                activities: [
                    { icon: iconMap.CiForkAndKnife, name: "Bridge Tour", description: "Take a guided tour of the most iconic bridges in New York." },
                    { icon: iconMap.CiTrophy, name: "Historical Insights", description: "Learn about the history and architecture of each bridge." },
                    { icon: iconMap.FaShower, name: "Photography Session", description: "Capture stunning views of the bridges with expert guidance." },
                    { icon: iconMap.FaRegStar, name: "Engineering Discussion", description: "Engage in discussions about bridge engineering and design." },

                ],
                shortDescription: "Explore the architectural marvels of New York's iconic bridges with a guided tour and expert insights.",
                whatYoullDo: "Experience a comprehensive tour of New York's bridges, including historical insights and photography opportunities.",
                location: { latitude: 40.7128, longitude: -74.0060 }
            },
        ]

    },
    {
        id: 5,
        image: "https://www.w3schools.com/w3images/woods.jpg",
        name: "Emily",
        keyword: "outdoorsy",
        city: "Vancouver",
        country: "Canada",
        totalYears: 12,
        identity: 556677889,
        number: 5556666,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [11, 12, 13],
        locations: [
            {
                id: 11,
                image: "https://www.w3schools.com/w3images/mountains.jpg",
                live: false,
                title: "Mountain Hike",
                host: {
                    id: 5,
                    image: "https://www.w3schools.com/w3images/woods.jpg",
                    name: "Emily",
                    keyword: "outdoorsy",
                    city: "Vancouver",
                    country: "Canada",
                    totalYears: 12,
                    identity: 556677889,
                    number: 5556666,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [11, 12, 13]
                },
                hostId: 5,
                isComingSoon: true,
                coming: "May",
                city: "Denver",
                country: "USA",
                guestrooms: 2,
                beds: 2,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-11-30",
                activities: [
                    { icon: iconMap.FaRegStar, name: "Guided Hike", description: "Enjoy a guided hike through the mountainous terrain." },
                    { icon: iconMap.IoHomeOutline, name: "Wildlife Spotting", description: "Look out for local wildlife during the hike." },
                    { icon: iconMap.PiCoatHangerThin, name: "Photography", description: "Capture stunning mountain views with expert tips." },

                ],
                shortDescription: "Experience the beauty of the mountains with a guided hike and various outdoor activities.",
                whatYoullDo: "Hike through scenic trails, spot wildlife, and enjoy a picnic lunch with breathtaking views.",
                location: { latitude: 39.7392, longitude: -104.9903 }
            },
            {
                id: 12,
                image: "https://www.w3schools.com/w3images/nature.jpg",
                live: true,
                title: "Nature Walk",
                host: {
                    id: 5,
                    image: "https://www.w3schools.com/w3images/woods.jpg",
                    name: "Emily",
                    keyword: "outdoorsy",
                    city: "Vancouver",
                    country: "Canada",
                    totalYears: 12,
                    identity: 556677889,
                    number: 5556666,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [11, 12, 13]
                },
                hostId: 5,
                price: 45,
                city: "Portland",
                country: "USA",

                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-10-15",
                activities: [
                    { icon: iconMap.CiForkAndKnife, name: "Nature Trail Walk", description: "Explore beautiful nature trails guided by an expert." },

                    { icon: iconMap.BsJournalAlbum, name: "Bird Watching", description: "Observe and identify various bird species." },
                    { icon: iconMap.CiTrophy, name: "Nature Photography", description: "Capture the beauty of nature with guidance from a photographer." },

                ],
                shortDescription: "Enjoy a guided nature walk and learn about local flora and fauna while capturing beautiful moments.",
                whatYoullDo: "Walk through nature trails, identify plants and birds, and capture stunning photographs.",
                location: { latitude: 45.5152, longitude: -122.6784 }
            },
            {
                id: 13,
                image: "https://www.w3schools.com/w3images/forest.jpg",
                live: true,
                title: "Forest Camping",
                host: {
                    id: 5,
                    image: "https://www.w3schools.com/w3images/woods.jpg",
                    name: "Emily",
                    keyword: "outdoorsy",
                    city: "Vancouver",
                    country: "Canada",
                    totalYears: 12,
                    identity: 556677889,
                    number: 5556666,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [11, 12, 13]
                },
                hostId: 5,
                soldOut: true,
                city: "Asheville",
                country: "USA",
                guestrooms: 3,
                beds: 6,
                bedrooms: 3,
                baths: 2,
                closingDate: "2024-09-25",
                activities: [

                    { icon: iconMap.FaRegStar, name: "Campfire Cooking", description: "Cook delicious meals over a campfire with expert tips." },

                    { icon: iconMap.BsJournalAlbum, name: "Forest Hiking", description: "Explore nearby forest trails with a guide." },
                    { icon: iconMap.TbBeach, name: "Wildlife Observation", description: "Observe and learn about local wildlife." },
                ],
                shortDescription: "Immerse yourself in nature with a camping experience in the forest, including guided hikes and stargazing.",
                whatYoullDo: "Set up camp, cook over a fire, hike the forest trails, and enjoy stargazing and wildlife observation.",
                location: { latitude: 35.6009, longitude: -82.5540 }
            },
        ]
    },
    {
        id: 6,
        image: "https://www.w3schools.com/w3images/forest.jpg",
        name: "Carlos",
        keyword: "lively",
        city: "Barcelona",
        country: "Spain",
        totalYears: 9,
        identity: 667788990,
        number: 6667777,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [14, 15],
        locations: [
            {
                id: 14,
                image: "https://www.w3schools.com/w3images/lights.jpg",
                live: false,
                title: "City Lights Tour",
                host: {
                    id: 6,
                    image: "https://www.w3schools.com/w3images/forest.jpg",
                    name: "Carlos",
                    keyword: "lively",
                    city: "Barcelona",
                    country: "Spain",
                    totalYears: 9,
                    identity: 667788990,
                    number: 6667777,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [14, 15]
                },
                hostId: 6,

                isComingSoon: true,
                coming: "july",
                city: "Los Angeles",
                country: "USA",
                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-12-10",
                activities: [
                    { icon: iconMap.FaRegStar, name: "City Night Tour", description: "Explore the city’s most famous landmarks lit up at night." },
                    { icon: iconMap.FaRegStar, name: "Photography Tips", description: "Receive tips on capturing city lights and night scenes." },
                    { icon: iconMap.FaRegStar, name: "Dinner at a Landmark", description: "Enjoy dinner at a well-known landmark with a view of the city." },
                    { icon: iconMap.FaRegStar, name: "Local History", description: "Learn about the history and significance of various city landmarks." },
                    { icon: iconMap.FaRegStar, name: "Nightlife Exploration", description: "Experience the city’s nightlife with guided tours of popular spots." },
                ],
                shortDescription: "Discover the beauty of city lights with a guided night tour and photography tips, including a special dinner experience.",
                whatYoullDo: "Tour iconic city landmarks at night, enjoy a special dinner, and explore the nightlife with expert guidance.",
                location: { latitude: 34.0522, longitude: -118.2437 }
            },
            {
                id: 15,
                image: "https://www.w3schools.com/w3images/mountains.jpg",
                live: true,
                title: "Mountain Retreat",
                host: {
                    id: 6,
                    image: "https://www.w3schools.com/w3images/forest.jpg",
                    name: "Carlos",
                    keyword: "lively",
                    city: "Barcelona",
                    country: "Spain",
                    totalYears: 9,
                    identity: 667788990,
                    number: 6667777,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [14, 15]
                },
                hostId: 6,
                price: 200,
                city: "Aspen",
                country: "USA",
                guestrooms: 4,
                beds: 8,
                bedrooms: 4,
                baths: 3,
                closingDate: "2024-11-30",
                activities: [

                    { icon: iconMap.CiTrophy, name: "Spa Sessions", description: "Enjoy spa treatments and massages in a tranquil environment." },
                    { icon: iconMap.CiCalendarDate, name: "Guided Hikes", description: "Participate in guided hikes to explore the beautiful mountain terrain." },
                    { icon: iconMap.PiMountains, name: "Yoga Classes", description: "Join yoga classes designed to enhance relaxation and wellness." },

                ],
                shortDescription: "Escape to a luxurious mountain retreat offering relaxation, guided hikes, spa sessions, and gourmet dining.",
                whatYoullDo: "Relax in a luxury mountain setting, participate in wellness activities, and enjoy gourmet dining and guided hikes.",
                location: { latitude: 39.1910, longitude: -106.8175 }
            },
        ]
    },
    {
        id: 7,
        image: "https://www.w3schools.com/w3images/mountains2.jpg",
        name: "Aisha",
        keyword: "historical",
        city: "Cairo",
        country: "Egypt",
        totalYears: 7,
        identity: 778899001,
        number: 7778888,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [16, 17],
        locations: [
            {
                id: 16,
                image: "https://www.w3schools.com/w3images/mountains.jpg",
                live: true,
                title: "Historic House Visit",
                host: {
                    id: 7,
                    image: "https://www.w3schools.com/w3images/mountains2.jpg",
                    name: "Aisha",
                    keyword: "historical",
                    city: "Cairo",
                    country: "Egypt",
                    totalYears: 7,
                    identity: 778899001,
                    number: 7778888,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [16, 17]
                },
                hostId: 7,
                price: 85,
                city: "Philadelphia",
                country: "USA",
                isComingSoon: true,
                coming: "October",
                guestrooms: 2,
                beds: 4,
                bedrooms: 2,
                baths: 2,
                closingDate: "2024-10-30",
                activities: [
                    { icon: iconMap.CiHeart, name: "Historical Tour", description: "Explore the historic house with a guided tour." },
                    { icon: iconMap.CiDesktop, name: "Architectural Insights", description: "Learn about the architectural style and history." },
                    { icon: iconMap.CiTrophy, name: "Period Costume Exhibition", description: "See costumes and artifacts from the era." },
                    { icon: iconMap.PiCoatHangerThin, name: "Q&A Session", description: "Engage in a Q&A session with the historian." },
                    { icon: iconMap.BsJournalAlbum, name: "Tea and Snacks", description: "Enjoy tea and snacks in a historical setting." },
                ],
                shortDescription: "Step back in time with a guided tour of a historic house, complete with insights into its architecture and period artifacts.",
                whatYoullDo: "Tour the house, learn about its history and architecture, enjoy a period costume exhibition, and partake in tea and snacks.",
                location: { latitude: 39.9526, longitude: -75.1652 }
            },
            {
                id: 17,
                image: "https://www.w3schools.com/w3images/bridge.jpg",
                live: false,
                title: "Bridge Photography Workshop",
                host: {
                    id: 7,
                    image: "https://www.w3schools.com/w3images/mountains2.jpg",
                    name: "Aisha",
                    keyword: "historical",
                    city: "Cairo",
                    country: "Egypt",
                    totalYears: 7,
                    identity: 778899001,
                    number: 7778888,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [16, 17]
                },
                hostId: 7,
                soldOut: true,
                city: "San Francisco",
                country: "USA",
                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-09-15",
                activities: [
                    { name: "Photography Techniques", description: "Learn techniques for photographing bridges." },
                    { name: "Field Photography", description: "Practice your skills on iconic local bridges." },
                    { name: "Editing Tips", description: "Get tips on editing bridge photos." },
                    { name: "Composition Workshop", description: "Understand composition principles for stunning bridge photos." },
                    { name: "Portfolio Review", description: "Receive feedback on your photography portfolio." },
                ],
                shortDescription: "Master the art of bridge photography with hands-on sessions and expert tips in this comprehensive workshop.",
                whatYoullDo: "Learn and practice photography techniques, explore local bridges, receive editing tips, and get feedback on your work.",
                location: { latitude: 37.7749, longitude: -122.4194 }
            },
        ]
    },
    {
        id: 8,
        image: "https://www.w3schools.com/w3images/lights2.jpg",
        name: "Lars",
        keyword: "cosy",
        city: "Copenhagen",
        country: "Denmark",
        totalYears: 4,
        identity: 889900112,
        number: 8889999,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [18],
        locations: [
            {
                id: 18,
                image: "https://www.w3schools.com/w3images/forest.jpg",
                live: true,
                title: "Wildlife Safari",
                host: {
                    id: 8,
                    image: "https://www.w3schools.com/w3images/lights2.jpg",
                    name: "Lars",
                    keyword: "cosy",
                    city: "Copenhagen",
                    country: "Denmark",
                    totalYears: 4,
                    identity: 889900112,
                    number: 8889999,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [18]
                },
                hostId: 8,
                price: 250,
                city: "Nairobi",
                country: "Kenya",
                guestrooms: 3,
                beds: 6,
                bedrooms: 3,
                baths: 2,
                closingDate: "2024-11-15",
                activities: [
                    { icon: iconMap.FaRegStar, name: "Game Drive", description: "Embark on a thrilling game drive to spot wildlife." },
                    { icon: iconMap.PiMountains, name: "Bird Watching", description: "Observe and identify various bird species." },
                    { icon: iconMap.GiFullMotorcycleHelmet, name: "Nature Walk", description: "Take a guided nature walk with a wildlife expert." },
                    { icon: iconMap.IoBedOutline, name: "Photography Session", description: "Capture stunning wildlife photographs with guidance." },
                    { icon: iconMap.MdOutlineFireplace, name: "Cultural Experience", description: "Learn about local cultures and traditions." },
                ],
                shortDescription: "Experience the thrill of a wildlife safari with guided game drives, bird watching, and cultural insights.",
                whatYoullDo: "Go on game drives, observe birds, take nature walks, capture wildlife photographs, and learn about local cultures.",
                location: { latitude: -1.2864, longitude: 36.8172 }
            },
        ]
    },
    {
        id: 9,
        image: "https://www.w3schools.com/w3images/snow.jpg",
        name: "Nina",
        keyword: "romantic",
        city: "Paris",
        country: "France",
        totalYears: 11,
        identity: 990011223,
        number: 9990000,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [19, 20],
        locations: [
            {
                id: 19,
                image: "https://www.w3schools.com/w3images/mountains.jpg",
                live: true,
                title: "Lake Fishing",
                host: {
                    id: 9,
                    image: "https://www.w3schools.com/w3images/snow.jpg",
                    name: "Nina",
                    keyword: "romantic",
                    city: "Paris",
                    country: "France",
                    totalYears: 11,
                    identity: 990011223,
                    number: 9990000,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [19, 20]
                },
                hostId: 9,
                price: 70,
                city: "Lake Tahoe",
                country: "USA",
                guestrooms: 1,
                beds: 2,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-10-01",
                activities: [
                    { icon: iconMap.PiMountains, name: "Fishing Techniques", description: "Learn various fishing techniques for lake fishing." },
                    { icon: iconMap.IoBookOutline, name: "Fishing Gear Setup", description: "Get hands-on experience setting up fishing gear." },
                    { icon: iconMap.CiHeart, name: "Catch and Release", description: "Practice catch and release techniques." },
                    { icon: iconMap.BsStars, name: "Scenic Views", description: "Enjoy beautiful views of the lake and surrounding mountains." },
                    { icon: iconMap.CiCalendarDate, name: "Fishing Safety", description: "Understand safety measures and regulations for fishing." },
                ],
                shortDescription: "Enjoy a day of fishing on picturesque Lake Tahoe with expert guidance and beautiful surroundings.",
                whatYoullDo: "Learn fishing techniques, set up gear, practice catch and release, and enjoy scenic lake views.",
                location: { latitude: 38.9396, longitude: -120.0454 }
            },
            {
                id: 20,
                image: "https://www.w3schools.com/w3images/lights.jpg",
                live: false,
                title: "Luxury House Stay",
                host: {
                    id: 9,
                    image: "https://www.w3schools.com/w3images/snow.jpg",
                    name: "Nina",
                    keyword: "romantic",
                    city: "Paris",
                    country: "France",
                    totalYears: 11,
                    identity: 990011223,
                    number: 9990000,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [19, 20]
                },
                hostId: 9,
                isComingSoon: true,
                coming: "October",
                city: "Miami",
                country: "USA",
                guestrooms: 5,
                beds: 10,
                bedrooms: 5,
                baths: 4,
                closingDate: "2024-12-20",
                activities: [
                    { icon: iconMap.FaRegStar, name: "Exclusive Tour", description: "Get an exclusive tour of the luxury house." },
                    { icon: iconMap.BsJournalAlbum, name: "Private Pool Access", description: "Enjoy private access to the pool and amenities." },
                    { icon: iconMap.CiForkAndKnife, name: "Gourmet Dining", description: "Experience gourmet dining with a personal chef." },
                    { icon: iconMap.BsStars, name: "Spa Services", description: "Indulge in spa services and wellness treatments." },
                    { icon: iconMap.BiMoviePlay, name: "Personalized Service", description: "Receive personalized service and attention during your stay." },
                ],
                shortDescription: "Experience luxury living with exclusive tours, private pool access, gourmet dining, and personalized service.",
                whatYoullDo: "Tour the luxury house, enjoy private amenities, dine with a personal chef, and receive personalized service.",
                location: { latitude: 25.7617, longitude: -80.1918 }
            },
        ]
    },
    {
        id: 10,
        image: "https://www.w3schools.com/w3images/bridge.jpg",
        name: "Luca",
        keyword: "gastronomic",
        city: "Florence",
        country: "Italy",
        totalYears: 15,
        identity: 111122334,
        number: 1112333,
        description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
        places: [21, 22],
        locations: [
            {
                id: 21,
                image: "https://www.w3schools.com/w3images/lights.jpg",
                live: true,
                title: "Night Photography Tour",
                host: {
                    id: 10,
                    image: "https://www.w3schools.com/w3images/bridge.jpg",
                    name: "Luca",
                    keyword: "gastronomic",
                    city: "Florence",
                    country: "Italy",
                    totalYears: 15,
                    identity: 111122334,
                    number: 1112333,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [21, 22]
                },
                hostId: 10,
                price: 95,
                city: "New York",
                country: "USA",

                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-11-05",
                activities: [
                    { icon: iconMap.IoBedOutline, name: "Night Photography Techniques", description: "Learn techniques for capturing stunning night photos." },
                    { icon: iconMap.GiFullMotorcycleHelmet, name: "City Tour", description: "Tour iconic city landmarks at night." },
                    { icon: iconMap.PiCoatHangerThin, name: "Composition Workshop", description: "Understand composition principles for night photography." },
                    { icon: iconMap.FaRegStar, name: "Post-Processing Tips", description: "Receive tips on editing night photos." },
                    { icon: iconMap.PiMountains, name: "Portfolio Review", description: "Get feedback on your night photography portfolio." },
                ],
                shortDescription: "Explore the city at night with expert guidance on photography techniques and editing tips.",
                whatYoullDo: "Learn night photography techniques, tour city landmarks, and receive feedback on your work.",
                location: { latitude: 40.7128, longitude: -74.0060 }
            },
            {
                id: 22,
                image: "https://www.w3schools.com/w3images/bridge.jpg",
                live: true,
                title: "Historical Bridge Walk",
                host: {
                    id: 10,
                    image: "https://www.w3schools.com/w3images/bridge.jpg",
                    name: "Luca",
                    keyword: "gastronomic",
                    city: "Florence",
                    country: "Italy",
                    totalYears: 15,
                    identity: 111122334,
                    number: 1112333,
                    description: " I’m your average girl that’s not-so-average sized. But even though I’m tiny, there’s no adventure too big for me to conquer. Whether it’s hanging ten on a surfboard or rocking the runway, I’m always down for a new epic experience, especially if my BFFs are along for the ride..",
                    places: [21, 22]
                },
                hostId: 10,
                soldOut: true,
                city: "London",
                country: "UK",
                guestrooms: 1,
                beds: 1,
                bedrooms: 1,
                baths: 1,
                closingDate: "2024-10-10",
                activities: [
                    { icon: iconMap.FaRegStar, name: "Bridge Tour", description: "Take a guided tour of historical bridges." },
                    { icon: iconMap.CiTrophy, name: "Historical Insights", description: "Learn about the history and significance of each bridge." },
                    { icon: iconMap.BsJournalAlbum, name: "Photography Session", description: "Capture stunning photos of historic bridges." },
                    { icon: iconMap.TbBeach, name: "Cultural Context", description: "Understand the cultural impact of the bridges." },
                    { icon: iconMap.CiHeart, name: "Q&A Session", description: "Engage in a Q&A session with the guide." },
                ],
                shortDescription: "Discover the history of iconic bridges with a guided walk and photography opportunities.",
                whatYoullDo: "Tour historic bridges, learn about their significance, capture photos, and engage in a Q&A session.",
                location: { latitude: 51.5074, longitude: -0.1278 }
            },
        ]
    }
];

export default Hosts;