export { default as HomePage } from './home';
export { default as CardDetail } from './Card';
export { default as HostDetail } from './host';
export { default as Payment } from './payment';
export { default as ProfilePage } from './profile';
export { default as SignInPage } from './auth/signin';
export { default as Notifications } from './notifications/index';
export { default as Private } from './privatechat/index';
export { default as ContactSection } from './common/contactUs'